version: "3.9"

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ~/sessions
    ports:
      - 40000:80
    environment:
      PMA_HOST: db.cfc101t.link  #在改ip
      PMA_USER: admin
      PMA_PASSWORD: wordpress
      
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ~/wordpress/www/html:/var/www/html    
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db.cfc101t.link
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}

